pipeline {
    agent {
        docker {
            image 'node:16-alpine'
        }
    }
    options {
        skipDefaultCheckout()
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm  // This will now happen inside the container
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run tests') {
            steps {
                sh 'npm test'
            }
        }
        stage('Build Project') {
            steps {
                sh 'npm run build'
            }
        }
        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'dist/**', fingerprint: true
            }
        }
    }
}

