pipeline {
    agent none

    stages {
        stage('Checkout and Build') {
            agent {
                docker {
                    image 'node:16-alpine'
                }
            }
            options {
                skipDefaultCheckout()
            }
            steps {
                checkout scm

                // Navigate to correct folder
                dir('Nodejs_App') {
                    sh 'ls -la'           // Check files
                    sh 'npm install'     // Install deps
                    sh 'npm test'        // Run tests
                    sh 'npm run build'   // Build
                }
            }
            post {
                success {
                    archiveArtifacts artifacts: 'Nodejs_App/dist/**', fingerprint: true
                }
            }
        }
    }
}

